# Generated by Django 5.1.1 on 2024-10-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_incident_human_intervention_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_color',
            field=models.CharField(default='#e0e5ec', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='layout',
            field=models.CharField(choices=[('default', 'Default'), ('compact', 'Compact'), ('spacious', 'Spacious')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='menu_position',
            field=models.CharField(choices=[('top', 'Top'), ('left', 'Left')], default='top', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shadow_color',
            field=models.CharField(default='#a3b1c6', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
