# Generated by Django 5.1.1 on 2024-12-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_knoxauthtoken_incident_pagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font_style',
            field=models.CharField(default='Arial', max_length=50),
        ),
    ]
