# Generated by Django 5.1.1 on 2024-12-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_font_color_userprofile_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logo_position',
            field=models.CharField(default='top-left', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logo_shape',
            field=models.CharField(default='rectangle', max_length=50),
        ),
    ]
