# Generated by Django 5.1.1 on 2024-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jiraticket_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationmspconfig',
            name='jira_api_base_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integrationmspconfig',
            name='jira_api_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='integrationmspconfig',
            name='jira_project_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='integrationmspconfig',
            name='jira_project_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='integrationmspconfig',
            name='jira_user_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jiraticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jiraticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
