# Generated by Django 5.1.1 on 2024-12-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_integrationmspconfig_jira_api_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraticket',
            name='issue_key',
            field=models.CharField(max_length=50),
        ),
    ]
