# Generated by Django 5.1.1 on 2024-12-06 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_jiraticket_issue_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jiraticket',
            unique_together={('user', 'issue_key')},
        ),
    ]
