# Generated by Django 5.1.1 on 2024-12-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_jiraticket_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jiraticket',
            name='predicted_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jiraticket',
            name='predicted_resolution_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
