# Generated by Django 5.1.1 on 2024-12-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_modelmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmanagement',
            name='file',
            field=models.FileField(null=True, upload_to='models/'),
        ),
        migrations.AddField(
            model_name='modelmanagement',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelmanagement',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='modelmanagement',
            name='size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelmanagement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10),
        ),
    ]
